version: "3.2"
services:
  sql-server:
    container_name: sql-server
    network_mode: bridge
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - "MSSQL_SA_PASSWORD=Pass@word"
      - "ACCEPT_EULA=Y"
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./config/elasticmq.conf:/opt/config/elasticmq.conf