name: build and test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  
  build-and-test:
      name: Build and Test
      runs-on: ubuntu-latest
      
      env:
        ASPNETCORE_ENVIRONMENT: Development
        AWS_COLABORA_ACCESS_KEY: access-key
        AWS_COLABORA_SECRET_KEY: secret
        SQL_COLABORA_DATABASE: Host=localhost;Port=5432;Database=COLABORA;User Id=testuser;Password=testpassword
      
      steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Run Unit Tests
        run: dotnet test --filter FullyQualifiedName~Colabora.UnitTests --no-restore --verbosity normal
        
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Run Integration Tests
        run: dotnet test --filter FullyQualifiedName~Colabora.IntegrationTests --no-restore --verbosity normal
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
        
  deploy-api-hml:
      name: Deploy API - Staging
      runs-on: ubuntu-latest
      needs: [ build-and-test ]
      
      permissions:
        id-token: write
        contents: read
      
      steps:
        - uses: actions/checkout@v3

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
  
        - name: AWS CLI
          run: dotnet tool install -g Amazon.Lambda.Tools
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            aws-region: sa-east-1

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release --no-restore        
          
        - name: Deploy to Lambda
          run: dotnet lambda deploy-function --function-name Colabora --project-location ./src/Colabora.WebAPI/ --region sa-east-1